<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_icon-rank-army-star-2</name>
   <tag></tag>
   <elementGuidId>8ee7cc22-ce08-4619-b00c-c421f9c0bc0b</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-rank-army-star-2</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;hauni&quot;]/div[@class=&quot;container&quot;]/hauni-customer-app[1]/hauni-projects[1]/hauni-project-detail[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;ng-star-inserted&quot;]/hauni-project-home[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-8 ng-star-inserted&quot;]/hauni-project-home-detail[1]/div[@class=&quot;card-deck--basic&quot;]/div[@class=&quot;card card--basic&quot;]/div[@class=&quot;card__title d-flex justify-content-between align-items-center card__title--inline-edit&quot;]/div[@class=&quot;project-room__actions d-flex align-items-center justify-content-between&quot;]/div[@class=&quot;mr-5&quot;]/i[@class=&quot;icon-rank-army-star-2&quot;]</value>
   </webElementProperties>
</WebElementEntity>
