<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_reopen</name>
   <tag></tag>
   <elementGuidId>41305f0e-9fa9-4fc9-93bf-d77f5cde18b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.project-list-item__reopen-project</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
